name: pytest-pr-check
on:
  pull_request:
    branches: [main]
env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
# permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
    Pytest:
      runs-on: ubuntu-latest
      steps:
        - name: checkout eks ml pipeline
          uses: actions/checkout@v3
          with:
            path: main
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            role-session-name: ${{ secrets.ROLE_SESSION_NAME }}
            aws-region: ${{ env.AWS_REGION }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install  pytest
            pip install s3fs
            pip install -r requirements.txt
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Install devex
          run: |
            pip install git+https://github.com/DISHDevEx/dish-devex-sdk.git
        - name: Test with pytest
          env:
            ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
            ROLE_SESSION_NAME: ${{ secrets.ROLE_SESSION_NAME }}
            BUCKET_NAME_PYTEST: ${{ secrets.BUCKET_NAME_PYTEST }}
            PYTEST_FLAG:  "True"
          run: |
            python --version
            pytest --slow
